version: "3.2"
services:
  mysql_database:
    container_name: user-container
    image: mysql:8.0.22
    volumes:
      - ~/docker/mysql/demo/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/demo/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/demo/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=ggundb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    networks:
      - test_env
  mongo_database:
    container_name: db-container
    image: mongo
    volumes:
      - ~/docker/mongo/db/etc/mongo/conf.d:/etc/mongo/conf.d:ro
      - ~/docker/mongo/db/var/lib/mongo:/var/lib/mongo
      - ~/docker/mongo/db/var/log/mongo:/var/log/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=ggundb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - test_env

networks:
  test_env:
    driver: bridge