version: '3.8'
services:
  zookeeper:
    image: zookeeper-dev
    container_name: zookeeper-dev
    ports:
      - "2181:2181"

  kafka:
    image: kafka-dev
    container_name: kafka-dev
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    container_name: mysql-dev
    image: mysql-dev
    volumes:
      - ./mysql/ggun/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/ggun/var/lib/mysql:/var/lib/mysql
      - ./mysql/ggun/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=ggundb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    restart: always

  mongodb:
    container_name: mongodb-dev
    image: mongo-dev
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/ggun:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=ggundb
    restart: always

  redis:
    container_name: redis-dev
    image: redis-dev
    ports:
      - 6379:6379
    command: redis-server --requirepass password
    volumes:
      - ./redis/data/ggun:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always

  postgres:
    container_name: postgres-dev
    image: postgres-dev
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ggundb
    restart: always